<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OTOHEROES Smartphone Car Holder Adjustable with Suction Cup - T003</name>
   <tag></tag>
   <elementGuidId>15740905-d9e4-42ef-8e17-8c9c15168a65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-list']/form/div[2]/div[2]/div[2]/div/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pi__name.link.link--normal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7dc049a4-d4d2-42ce-a0a7-59da1251b58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.jakmall.com/fast-n-cheap/otoheroes-smartphone-car-holder-adjustable-with-suction-cup-t003?jtm=789c8b564a4e2c494dcf2faa54d2512a28ca4f294d2ed1cdc92c2e01728b2b8b755185f24a737274a263630113eb1366#6778950816597</value>
      <webElementGuid>0da9e3d1-66dc-4260-a001-0cfa92340243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>OTOHEROES Smartphone Car Holder Adjustable with Suction Cup - T003</value>
      <webElementGuid>3141a694-1d0a-4557-b82a-352ebcb65fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pi__name link link--normal</value>
      <webElementGuid>ac04d116-4e4c-4da8-8c89-a67223ae3aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OTOHEROES Smartphone Car Holder Adjustable with Suction Cup - T003</value>
      <webElementGuid>9f1a0a13-7e46-467e-b663-bf584dadd69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-list&quot;)/form[1]/div[@class=&quot;container plist__filter__container&quot;]/div[@class=&quot;plist__container scrollto__section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;pi__wrapper&quot;]/div[@class=&quot;pi pi__default pl__sizer&quot;]/div[@class=&quot;pi__core&quot;]/div[@class=&quot;pi__body&quot;]/a[@class=&quot;pi__name link link--normal&quot;]</value>
      <webElementGuid>4e1248af-3412-49da-a0ad-0a34f7d48a6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-list']/form/div[2]/div[2]/div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>a2d5ffa6-8826-488b-8cd4-fcf22442b6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'OTOHEROES Smartphone Car Holder Adjustable with Suction Cup - T003')])[2]</value>
      <webElementGuid>d7642cbb-e0a1-4af0-811f-470af4b68e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_right'])[2]/following::a[2]</value>
      <webElementGuid>fbbc9a1d-90c8-46b7-9c5a-f520c5f59e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/following::a[5]</value>
      <webElementGuid>1402ed54-a412-4465-968a-9f15b0bf8c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hitam'])[9]/preceding::a[1]</value>
      <webElementGuid>bc1ac54e-2817-40ae-a2cd-eb581f060761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[1]/preceding::a[1]</value>
      <webElementGuid>d311809b-b494-4a9e-adc1-0402db9d9371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.jakmall.com/fast-n-cheap/otoheroes-smartphone-car-holder-adjustable-with-suction-cup-t003?jtm=789c8b564a4e2c494dcf2faa54d2512a28ca4f294d2ed1cdc92c2e01728b2b8b755185f24a737274a263630113eb1366#6778950816597')])[2]</value>
      <webElementGuid>ac4b5871-e5a4-473e-a4e1-8d874d9c6470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>e1480489-cf12-4de0-b421-7d5943794482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.jakmall.com/fast-n-cheap/otoheroes-smartphone-car-holder-adjustable-with-suction-cup-t003?jtm=789c8b564a4e2c494dcf2faa54d2512a28ca4f294d2ed1cdc92c2e01728b2b8b755185f24a737274a263630113eb1366#6778950816597' and @title = 'OTOHEROES Smartphone Car Holder Adjustable with Suction Cup - T003' and (text() = 'OTOHEROES Smartphone Car Holder Adjustable with Suction Cup - T003' or . = 'OTOHEROES Smartphone Car Holder Adjustable with Suction Cup - T003')]</value>
      <webElementGuid>4316aa32-f09b-40e2-ab29-b63b76829fb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
