<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>95ae5dbd-81f1-4bb4-8386-7966e0e3df77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pclp']/div[3]/div[2]/div/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e835c708-a9c1-4326-ac56-9ca0793630a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.jakmall.com/images/desktop/product/category-landing-page/favorite-category/tablet.png</value>
      <webElementGuid>c530d3e8-5ec2-42eb-b20f-7edd1b745c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pclp&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;pclp__favorite__category__wrapper&quot;]/div[@class=&quot;pclp__favorite__categories&quot;]/div[@class=&quot;pclp__favorite__category&quot;]/div[@class=&quot;pclp__favorite__category__banner__wrapper&quot;]/a[1]/img[1]</value>
      <webElementGuid>328594b8-491e-4c5a-883d-e9c4bbe5d55c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pclp']/div[3]/div[2]/div/div[2]/div/a/img</value>
      <webElementGuid>e105b6c0-d82f-4494-8153-00ebf85c5e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.jakmall.com/images/desktop/product/category-landing-page/favorite-category/tablet.png')]</value>
      <webElementGuid>a2c48b32-eb67-472e-b213-bf2199b4113b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/a/img</value>
      <webElementGuid>856720ea-9671-436b-892e-6dbf4855d6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.jakmall.com/images/desktop/product/category-landing-page/favorite-category/tablet.png']</value>
      <webElementGuid>bfe7750c-49f6-4799-add7-2483e8cdd4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pclp']/div[3]/div[2]/div/div[7]/div/a/img</value>
      <webElementGuid>8575c994-66e4-4beb-98d7-0550c6ae3987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.jakmall.com/images/desktop/product/category-landing-page/favorite-category/adaptor-charger.png')]</value>
      <webElementGuid>6d4d77df-4670-4f09-bf34-fe34f141bb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/a/img</value>
      <webElementGuid>66d6bf13-2c19-4d33-b51e-b0f29fdd00c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.jakmall.com/images/desktop/product/category-landing-page/favorite-category/adaptor-charger.png']</value>
      <webElementGuid>02ad0ae7-81bf-43ef-aaec-1691c6b7d956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
