<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>4108f720-851f-4bd0-9d7a-f373cf79a9bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pclp']/div[3]/div[2]/div/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d22f1a5c-ac2b-4fac-9fe6-edd2e152ba4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.jakmall.com/images/desktop/product/category-landing-page/favorite-category/tablet.png</value>
      <webElementGuid>e34fc683-b40c-4e46-a854-36ffc92b5df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pclp&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;pclp__favorite__category__wrapper&quot;]/div[@class=&quot;pclp__favorite__categories&quot;]/div[@class=&quot;pclp__favorite__category&quot;]/div[@class=&quot;pclp__favorite__category__banner__wrapper&quot;]/a[1]/img[1]</value>
      <webElementGuid>ae364fdc-db67-46d9-b044-bcca6d11720c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pclp']/div[3]/div[2]/div/div[2]/div/a/img</value>
      <webElementGuid>31ed0cf1-51bc-46c3-92e3-6f07d805d505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.jakmall.com/images/desktop/product/category-landing-page/favorite-category/tablet.png')]</value>
      <webElementGuid>c9c3b013-4a30-41a4-b9e7-cd00200598a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/a/img</value>
      <webElementGuid>237613e6-9756-41d8-9f17-b82c34f32c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.jakmall.com/images/desktop/product/category-landing-page/favorite-category/tablet.png']</value>
      <webElementGuid>279fbe98-0717-4ef0-ac4a-2432f7fb01be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
